git clone https://coral.googlesource.com/imx-board-tools
git clone https://coral.googlesource.com/imx-firmware
git clone https://coral.googlesource.com/kokoro-enterprise
git clone https://coral.googlesource.com/linux-imx
git clone https://coral.googlesource.com/meta-enterprise
git clone https://coral.googlesource.com/meta-mendel
git clone https://coral.googlesource.com/uboot-imx
git clone https://coral.googlesource.com/All-Projects
git clone https://coral.googlesource.com/All-Users
git clone https://coral.googlesource.com/base-files
git clone https://coral.googlesource.com/build
git clone https://coral.googlesource.com/board-enterprise
git clone https://coral.googlesource.com/busybox
git clone https://coral.googlesource.com/bluez-imx
git clone https://coral.googlesource.com/bpt
git clone https://coral.googlesource.com/coral-cloud
git clone https://coral.googlesource.com/docs
git clone https://coral.googlesource.com/edgetpu
git clone https://coral.googlesource.com/edgetpudemo
git clone https://coral.googlesource.com/edgetpu-native
git clone https://coral.googlesource.com/edgetpuvision
git clone https://coral.googlesource.com/gasket-dkms-debian
git clone https://coral.googlesource.com/bluez-imx-debian
git clone https://coral.googlesource.com/gst-plugins-ugly1.0
git clone https://coral.googlesource.com/img2simg
git clone https://coral.googlesource.com/imx-atf
git clone https://coral.googlesource.com/imx-atf-debian
git clone https://coral.googlesource.com/imx-board-audio
git clone https://coral.googlesource.com/imx-board-wlan
git clone https://coral.googlesource.com/imx-board-wlan-src
git clone https://coral.googlesource.com/imx-firmware-debian
git clone https://coral.googlesource.com/imx-gst1.0-plugin
git clone https://coral.googlesource.com/imx-gst1.0-plugin-debian
git clone https://coral.googlesource.com/imx-gst-plugins-bad
git clone https://coral.googlesource.com/imx-gst-plugins-bad-debian
git clone https://coral.googlesource.com/imx-gst-plugins-base
git clone https://coral.googlesource.com/imx-gst-plugins-base-debian
git clone https://coral.googlesource.com/imx-gst-plugins-good
git clone https://coral.googlesource.com/imx-gst-plugins-good-debian
git clone https://coral.googlesource.com/imx-gstreamer
git clone https://coral.googlesource.com/imx-gstreamer-debian
git clone https://coral.googlesource.com/imx-mkimage
git clone https://coral.googlesource.com/imx-mkimage-debian
git clone https://coral.googlesource.com/libdrm-imx
git clone https://coral.googlesource.com/libdrm-imx-debian
git clone https://coral.googlesource.com/linux-imx-debian
git clone https://coral.googlesource.com/manifest
git clone https://coral.googlesource.com/mdt
git clone https://coral.googlesource.com/mdt-services
git clone https://coral.googlesource.com/mendel-distro-info-data
git clone https://coral.googlesource.com/mendel-keyring
git clone https://coral.googlesource.com/mendel-minimal
git clone https://coral.googlesource.com/prebuilts
git clone https://coral.googlesource.com/runonce
git clone https://coral.googlesource.com/uboot-imx-debian
git clone https://coral.googlesource.com/usb-gadget
git clone https://coral.googlesource.com/vitalsd
git clone https://coral.googlesource.com/wayland-protocols-imx
git clone https://coral.googlesource.com/wayland-protocols-imx-debian
git clone https://coral.googlesource.com/weston-imx
git clone https://coral.googlesource.com/weston-imx-debian


##https://coral.googlesource.com/?fbclid=IwAR0XnFYHATp_v_WkKOhtdiu1_YF6xnWVXvVLQmJ7izxjBWyezI9uennhzJY